### ISSUE TITLE
values_yaml on RenderEnvironment does not work for directories

### ISSUE THREAD

**Issue by SteinRobert** [unikubehq/commons#12]

**Comment by Schille** [comment]
This function to be rewritten to accept all value files in case a directory is given.
https://github.com/unikubehq/commons/blob/main/commons/helm/parser.py#L184-L192

**Comment by Schille** [comment]
All files with `.yaml` extension in the given directory must be concatenated read into `values_yaml`. Please confirm @SteinRobert 
However, `environment.values_path` can still point to a singe file. In that case apply the present logic.

**Comment by Schille** [comment]
Another hint: not just in theory, but also in practice there are same keys (or key-structures) in multiple yaml files. That means, there must be some sort of merge strategy.
